server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Intenta buscar el archivo, si no lo encuentra busca un directorio, 
        # y si no encuentra nada, devuelve el index.html
        try_files $uri $uri/ /index.html;
    }
}
